---
all:
  children:

    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

    kvm:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        docker_service_dir: /root/docker
      children:

        k8s-master:
          hosts:
            192.168.122.142:

        k8s-worker:
          hosts:
            192.168.122.36:
            192.168.122.6:
...        
