---
- name: create download dir
  file:
    path: "{{ role_path }}/files/"
    state: directory
    owner: "{{ groupVarAnsibleUser }}"
    group: "{{ groupVarAnsibleGroup }}"
    mode: 0755
  tags:
    - alpine
    - ubuntu
    
- name: Download Alpine.iso
  get_url:
    url: "{{ roleVarAlpineDownload }}"
    dest: "{{ role_path }}/files/{{ roleVarAlpineDownload | basename }}"
    checksum: "{{ roleVarAlpineDownloadChecksum }}"
    mode: 0666
  tags: alpine

- name: Download Ubuntu.iso
  get_url:
    url: "{{ roleVarUbuntuDownload }}"
    dest: "{{ role_path }}/files/{{ roleVarUbuntuDownload | basename }}"
    checksum: "{{ roleVarUbuntuDownloadChecksum }}"
    mode: 0666
  tags: ubuntu
...
