---
cluster_domain: "cluster.local"
canal_iface: ens3
download_rke: https://github.com/rancher/rke/releases/download/v0.3.0/rke_linux-amd64
download_rke_sha256: sha256:5cbcee455889d16ec95f7facffd6000e12306b4e946f6ba4a1e074d45fa6b3ba
...
